# Generated by Django 3.1.4 on 2021-01-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('nick_name', models.CharField(max_length=50, verbose_name='Nick Name')),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('password', models.CharField(max_length=25, verbose_name='Password')),
                ('address', models.CharField(max_length=50, verbose_name='Street Address')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('province', models.CharField(max_length=20, verbose_name='Province / State')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal / Zip Code')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
    ]
