# Generated by Django 3.1.4 on 2021-01-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(max_length=50, null=True, verbose_name='Product brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='year_of_manufacturer',
            field=models.IntegerField(null=True, verbose_name='Year of Manufacturer'),
        ),
    ]
