# Generated by Django 3.1.4 on 2021-01-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210103_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Name'),
        ),
    ]
